name: Checks for markdown

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run textlint ./src/pages/**/*.md
